project:
  type: website
  output-dir: docs

#website:
#  repo-url: https://github.com/BrainCircuitsIO/bcio-articles
#  repo-actions: [edit, issue]

format:
  html:
    theme: cosmo
    css: styles.css



